
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/clion-2025.2.3/bin/cmake/linux/x64/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/jarro/.local/bin/"
      - "/home/jarro/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/var/lib/snapd/snap/bin/"
      - "/opt/clion-2025.2.3/bin/ninja/linux/x64/"
      - "/bin/"
    searched_directories:
      - "/home/jarro/.local/bin/uname"
      - "/home/jarro/bin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/jarro/.local/bin"
        - "/home/jarro/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/var/lib/snapd/snap/bin"
        - "/opt/clion-2025.2.3/bin/ninja/linux/x64"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/clion-2025.2.3/bin/cmake/linux/x64/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 7.0.9-105.fc43.x86_64 - x86_64
...
